add etcd template resolver support
onlineconf/onlineconf pull request #55
Opened 2023-01-17 13:00 UTC by KaymeKaydex

- now you can resolve some etcd values with oc updater

2023-01-18 18:34 UTC, aleksey-mashanov requested changes

2023-01-19 08:16 UTC, KaymeKaydex commented on updater/main.go
> +	"github.com/onlineconf/onlineconf/updater/v3/updater/config"
yes, perhaps I will also add a linter

2023-01-19 08:20 UTC, KaymeKaydex commented on updater/main.go
> +	if config.ResolvePlugins.Enable {
yes, initially there was an idea to make an implementation through a plugin as a binary file, the main disadvantage is the need for an ecosystem and a minimal sdk, which is not advisable to do yet. I'll just rename it to resolvers

2023-01-19 08:21 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +			val, err := p.Resolve(context.TODO(), strings.TrimPrefix(key, p.Prefix()))
Yes, I will inherit the root

2023-01-19 11:23 UTC, KaymeKaydex commented on updater/updater/resolver-plugins/etcd/etcd.go
> +func (r *Resolver) Info() string {
initially, when creating a model of the resolver module, I want to capture in the logs what it is

2023-01-19 11:26 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +func TryResolveByResolverPlugins(key string) (resolved string, ok bool) {
convenience, to fix that also no one of the resolvers could not resolve, And not just an empty resolved string there. it doesn't matter if we decide to delete

2023-01-19 11:46 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +			val, err := p.Resolve(context.TODO(), strings.TrimPrefix(key, p.Prefix()))
done

2023-01-19 11:47 UTC, KaymeKaydex commented on updater/main.go
> +	"github.com/onlineconf/onlineconf/updater/v3/updater/config"
done

2023-01-19 11:50 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +type IResolverPlugin interface {
fixed

2023-01-19 11:52 UTC, KaymeKaydex commented on updater/updater/admin.go
> +				if vars[name] == "" {
fixed

2023-01-19 11:55 UTC, KaymeKaydex commented on updater/updater/resolver-plugins/etcd/etcd.go
> +func (r *Resolver) Info() string {
i removed; done

2023-01-19 11:58 UTC, KaymeKaydex commented on updater/etc/onlineconf.yaml
> +resolve_plugins:
I think the example should also be an example of a local startup, the values of xxx are a bit confusing; in general, it does not matter to me

2023-01-19 12:17 UTC, KaymeKaydex commented on updater/main.go
> +	if config.ResolvePlugins.Enable {
done

2023-01-19 12:19 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +func TryResolveByResolverPlugins(key string) (resolved string, ok bool) {
if no one plugin can resolve such value

2023-01-19 12:21 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +func TryResolveByResolverPlugins(key string) (resolved string, ok bool) {
i added log if no resolver could get the value

2023-01-19 12:35 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	if err == nil {
there is a log if the resolve module could not be started

2023-01-19 12:39 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	for _, p := range IncludedPlugins {
separator is :
in what way predictable? it seems that giving the resolver to recognize the prefix itself is less optimal than asking the resolver if it is his prefix

2023-01-19 19:04 UTC, aleksey-mashanov commented
Modifications of a variable in `etcd` must be propagated to the configuration files without requiring touching of OnlineConf tree.

2023-01-19 19:10 UTC, aleksey-mashanov requested changes

2023-01-23 13:26 UTC, KaymeKaydex commented on updater/etc/onlineconf.yaml
> +resolve_plugins:
this case is just an example. it disables all resolvers by default

2023-01-23 13:27 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +type IResolverPlugin interface {
I rname it from ModuleResolver to TemplateVariableResolver

2023-01-23 13:29 UTC, KaymeKaydex commented on updater/main.go
> +	if config.ResolvePlugins.Enable {
I found one place where the name of the plugin remained and fixed it, revised it now, it doesn't seem to be left

2023-01-23 13:40 UTC, KaymeKaydex commented on updater/main.go
> +	"github.com/onlineconf/onlineconf/updater/v3/updater/config"
done, fixed the sorting in my ide that was getting in the way

2023-01-23 14:40 UTC, KaymeKaydex commented on updater/main.go
> +		if u.Update(ctx) != nil {
how is the root context able to change the work of the api?

2023-01-23 14:41 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	for _, p := range IncludedPlugins {
you mean plugin:plugin_name:key?

2023-01-23 14:52 UTC, KaymeKaydex commented on updater/etc/onlineconf.yaml
> +resolve_plugins:
what's your suggestion?

2023-01-23 14:52 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	if err == nil {
what's your suggestion?

2023-01-24 12:27 UTC, aleksey-mashanov commented on updater/updater/template_resolvers.go
> +	if err == nil {
Die if an error emitted on the first run, use previous value in the other case.

2023-01-24 12:29 UTC, aleksey-mashanov commented on updater/updater/template_resolvers.go
> +	for _, p := range IncludedPlugins {
`${plugin_name}:${key}` to be compatible with vault injection syntax.

2023-01-24 12:30 UTC, aleksey-mashanov commented on updater/main.go
> +		if u.Update(ctx) != nil {
u.Update() – is a part of the public API and is used by onlineconf-csi-driver.

2023-01-25 08:51 UTC, aleksey-mashanov commented on updater/main.go
> -type AdminConfig struct {
No. They was intentionally split apart. `updater` is a public package and its AdminConfig is used to provide public API. AdminConfig in main is used for yaml-config parsing and must be backward compatible with previous versions to not force users to update config on minor version upgrade.

2023-01-25 14:21 UTC, KaymeKaydex commented on updater/etc/onlineconf.yaml
> +resolve_plugins:
I deleted everything new

2023-01-25 14:29 UTC, KaymeKaydex commented on updater/main.go
> +		if u.Update(ctx) != nil {
removed root ctx, now ctx is context.TODO with todo comment

2023-01-25 14:41 UTC, KaymeKaydex commented on updater/main.go
> -type AdminConfig struct {
I returned it to the old place

2023-01-25 14:46 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	for _, p := range IncludedPlugins {
I rplcd separator usage

2023-01-26 16:10 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	if err == nil {
check please current decision

2023-01-26 17:17 UTC, Nikolo requested changes

2023-01-26 17:17 UTC, Nikolo commented on updater/updater/template_resolvers.go
> +			ResolveChecker.Put(m, resolverKey, val)
А точно ли надо Put-ить значение в случае если произошла ошибка?

2023-01-26 17:17 UTC, Nikolo commented on updater/main.go
> +		updater.ResolveChecker = updater.NewResolveModulesValChecker(ctx, 10*time.Second, u.UpdateForce)
Magic num 10
Может в конфиг унести?

2023-01-26 17:17 UTC, Nikolo commented on updater/updater/template_resolvers.go
> +	tickReady       atomic.Bool
А зачем это поле? Предполагалось его использование?

2023-01-26 17:17 UTC, Nikolo commented on updater/updater/template_resolvers.go
> +	etcd, err := etcd.New(resolversCfgs[etcd.ResolverName])
На данном этапе предполагается, что т.к. резолвер один то если они включены то по любому надо попытаться подключить etcd?

Может сразу попробовать про конструкцию со switch case-ом или как то так? Боюсь, что если в resolversCfgs приедет, какое то отличное от etcd значение, и при этом не приедет etcd, то ошибка может выглядеть очень странно или непример её вообще не будет если etcd.New, переварит пустую конфигурацию.

2023-01-26 22:49 UTC, KaymeKaydex commented on updater/main.go
> +		go updater.ResolveChecker.StartCronCheck()
поправлю

2023-01-26 22:49 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +			ResolveChecker.Put(m, resolverKey, val)
да, чтобы если оно пустое на данный момент и потом станет не пустым то оно само починилось

2023-01-26 22:49 UTC, KaymeKaydex commented on updater/main.go
> +		updater.ResolveChecker = updater.NewResolveModulesValChecker(ctx, 10*time.Second, u.UpdateForce)
поправлю, забыл убрать после дебага

2023-01-26 22:50 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	tickReady       atomic.Bool
верно, поправлю

2023-01-26 22:50 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	etcd, err := etcd.New(resolversCfgs[etcd.ResolverName])
верно, поправлю

2023-01-27 09:15 UTC, KaymeKaydex commented on updater/main.go
> +		updater.ResolveChecker = updater.NewResolveModulesValChecker(ctx, 10*time.Second, u.UpdateForce)
исправил на config.UpdateInterval

2023-01-27 09:17 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	tickReady       atomic.Bool
поправил, убрал

2023-01-27 09:23 UTC, KaymeKaydex commented on updater/main.go
> +		go updater.ResolveChecker.StartCronCheck()
пофиксил

2023-01-27 09:45 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +			ResolveChecker.Put(m, resolverKey, val)
поговорили на эту тему, закроем тред

2023-01-30 07:29 UTC, KaymeKaydex commented on updater/updater/template_resolvers.go
> +	etcd, err := etcd.New(resolversCfgs[etcd.ResolverName])
добавил заглушкой с проверкой конфига на нил и todo: чтобы это не забыть сделать

2024-03-25 12:57 UTC, closed without merging