Fix vulnerabilities. Bump material-ui and any other libs versions
onlineconf/onlineconf pull request #74
Opened 2024-01-05 21:09 UTC by Nikolo

# Update deprecated and vulnerabilities dependencies

- Material-ui v4 -> v5
- react 16.14.2 -> 17.0.74

# Vulnerabilities stat
Before update:

```bash
% npm audit --omit=dev
16 vulnerabilities (6 moderate, 7 high, 3 critical)
```

After update:
```bash
% npm audit --omit=dev                                
found 0 vulnerabilities
```

2024-01-17 17:05 UTC, aleksey-mashanov commented
Wow! I will look at this closely a little bit later.
The only thing I want to comment right now is that admin/static/lib is third party libraries and better not to touch them at all.

2024-01-17 18:21 UTC, Nikolo commented
> Wow! I will look at this closely a little bit later. The only thing I want to comment right now is that admin/static/lib is third party libraries and better not to touch them at all.

It's autocorrection. I revert all changes in static/lib thanks!

2024-01-23 14:00 UTC, aleksey-mashanov commented
Please, test this PR carefully. It simply doesn't work as expected: UI is broken.

P.S. MUI upgrading usually is not an easy task. It requires days of extensive small modifications and careful testing of every UI component.

2024-01-23 14:03 UTC, aleksey-mashanov requested changes

2024-01-23 14:10 UTC, aleksey-mashanov commented
The problem of the broken UI can be as simple as forgotten step in the migration process. [This](https://mui.com/material-ui/migration/v5-style-changes/#%E2%9C%85-adjust-css-injection-order), for example.
But usually not. [Here](https://github.com/onlineconf/onlineconf/commit/5c36328d404ccb31ffcb085d5f05ddd497d67dc4) for reference is commit that upgraded MUI from v3 to v4.

2024-01-30 23:21 UTC, Nikolo commented on admin/js/src/components/Editor.tsx
> +export default withStyles(styles)(withTranslation()(Editor));
Fixed

2024-01-30 23:22 UTC, Nikolo commented on admin/js/src/components/ParamAccess.tsx
> +export default withStyles(styles)(withTranslation()(ParamAccess));
Fixed

2024-01-30 23:22 UTC, Nikolo commented on admin/js/src/components/Viewer.tsx
> +export default withStyles(styles)(withTranslation()(Viewer));
Fixed

2024-02-05 14:51 UTC, aleksey-mashanov commented
The UI looks good. I'll look at the code a little bit later.

2024-02-19 17:14 UTC, aleksey-mashanov reviewed
LGTM
Waiting for the approval from the QA.

2024-02-20 17:42 UTC, aleksey-mashanov approved these changes

2024-02-20 17:43 UTC, merged